baseURL: "https://jenkins-alex.github.io" 
title: Alexander Jenkins
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        - name: CV
          url: cv.pdf
          weight: 2

params:
    description: "This website hosts Alexander Jenkins's research papers, curriculum vitae, and contact information."
    author: Alexander Jenkins
    googleAnalyticsID: "G-VVMJ7FRD6K"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alexander Jenkins
          subtitle: "I am a PhD Researcher in the Department of Electrical and Electronic Engineering at Imperial College London, specialising in artificial intelligence and machine learning for healthcare applications, supervised by Prof Danilo Mandic and Dr Fu Siong Ng.<br><br>My research focuses on developing AI methods to understand complex heart rhythm disorders, particularly using graph neural networks and time series analysis. My work has resulted in publications at top-tier venues including ICML and two filed patents.<br><br>I have experience spanning academia, finance, and technology, including roles at University of Oxford, IDSIA Switzerland, and Hummingbird Venture Capital. I am currently exploring opportunities upon finishing my PhD in Winter 2025."
          imageUrl: "me.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            - name: CV
              url: cv.pdf

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:a.jenkins21@imperial.ac.uk
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=zAlYfWoAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/alexanderljenkins/
        - name: GitHub
          url: https://github.com/jenkins-alex
        - name: Substack
          url: https://substack.com/@alexanderjenkins
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alexander Jenkins"
      icon: favicon.ico
      iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2